language: node_js
node_js:
  - '8'
script:
  - npm run build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eanHTGfBWLjnQpbDnymwhnfjyi1xrKwqlHRelF/Sk8x/f51JF36y+Mj2vsJR9nv2oMv0RKz2IKyTvDXn6XzSLma0e77kTlg9rrB4o5sPKGLzo0pQVG0geKo4DLGz/406C5X2K99VPrwlHm3dq9PxXuEHrgrolx025g/dBBBh51AgCiALNGx12C5xK4E8/0B/zjPoKcKjnbSSee9ltkXDBMZvF7zwBixHm8duVJ9fFR6emaWH4X3zQpbZtPdqM7HgLTgvtfbjSEQazyAy5Y2F04e+0COURpjF5TbuNXRJogZRmpKUCMLwBHapRC0dx8cfmti91MR++CiDO83dtUxcVbGreawzQeM0pNHk/YLY39pCi/hHBe05wDBQXzVwnRrBxymQOoEOZpfsg2gKK5hS4be/CLS0VXO0R1j7DgGOuZ3/fGsRtBjjDU3hx0v0Am2+Rbg1nD9GnzW+Exw3EZnFMT4zl8bmql6zEhudo8gDuroYB5NZ2pD2ZUxIg9taPVATYAqSAWnMWRUs53fYAKfOpRIS8GE+ADNMmM0ugrl+VImLkuB+5UcBhEtUhR3C5xZqxdUw6new3B9WQYoycCBO6kkSGJe+5lDgGyQ61iCDqO8bPJnqQ+gS7MG5K/MAyC8+ghEfKHjTN9rDWbx76U7SJ6gXXTudtMdw8Md024mDS/I=
  file_glob: true
  file: build/dist/*
  on:
    tags: true
